### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by mouse07410** [bwesterb/draft-schwabe-cfrg-kyber#2]
MacOS 12.5, Python-3.10.5

```
$ make
git clone -q --depth 10  \
    -b main https://github.com/martinthomson/i-d-template lib
python3 -m venv /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.venv
/Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.venv/bin/python -m pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in ./lib/.venv/lib/python3.10/site-packages (22.0.4)
Collecting pip
  Downloading pip-22.2-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 21.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./lib/.venv/lib/python3.10/site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.2 setuptools-63.2.0 wheel-0.37.1
/Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.venv/bin/pip install -r lib/requirements.txt
Collecting archive-repo
  Using cached archive_repo-0.0.2-py3-none-any.whl (10 kB)
.  .  .
Installing kramdown-rfc 1.6.14
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Bundle complete! 2 Gemfile dependencies, 10 gems now installed.
Bundled gems are installed into `./lib/.gems`
Post-install message from certified:
IMPORTANT: Remember to use the included executable `certifed-update` regularly to keep your certificate bundle up to date.
cat draft-cfrg-schwabe-kyber.md  | kramdown-rfc --v3 | lib/trace.sh draft-cfrg-schwabe-kyber.xml -s venue /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.venv/bin/python lib/add-note.py | lib/trace.sh draft-cfrg-schwabe-kyber.xml -s v2v3 /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.venv/bin/xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/ur20980/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-cfrg-schwabe-kyber.xml
---
- No link definition for link ID 'x' found on line 233
/Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
/Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1069:in `read': execution expired (Net::OpenTimeout)
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1069:in `get_and_cache_resource'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1157:in `block in convert_img'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1143:in `scan'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1143:in `convert_img'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:335:in `block in inner_a'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:333:in `map'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:333:in `inner_a'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:340:in `inner'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:353:in `convert_p'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:335:in `block in inner_a'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:333:in `map'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:333:in `inner_a'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:340:in `inner'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:1395:in `convert_root'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:328:in `convert1'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc2629.rb:323:in `convert'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-2.4.0/lib/kramdown/converter/base.rb:107:in `convert'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-2.4.0/lib/kramdown/document.rb:116:in `method_missing'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/lib/kramdown-rfc/command.rb:575:in `<top (required)>'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/bin/kramdown-rfc:8:in `require'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/gems/kramdown-rfc2629-1.6.14/bin/kramdown-rfc:8:in `<top (required)>'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/bin/kramdown-rfc:29:in `load'
	from /Users/ur20980/src/draft-schwabe-cfrg-kyber/lib/.gems/bin/kramdown-rfc:29:in `<main>'
Error: Unable to parse the XML document: /dev/stdin
make: *** [lib/main.mk:72: draft-cfrg-schwabe-kyber.xml] Error 1
make: *** Deleting file 'draft-cfrg-schwabe-kyber.xml'
```

**Comment by bwesterb** [comment]
This might be it?

`*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml`

**Comment by mouse07410** [comment]
> This might be it?

I've no idea. 

Does this ton of stuff that the `make` gets involved, understand web proxy?

If not, may I suggest that the build process is flawed for corporate users?

**Comment by bwesterb** [comment]
> And, more importantly, how to fix it?

No clue. I’m new to this tooling as well, and I cannot reproduce your error myself.

**Comment by bwesterb** [comment]
Note that you can read the draft already [here](https://bwesterb.github.io/draft-schwabe-cfrg-kyber/draft-cfrg-schwabe-kyber.html) as CI builds it for us.

**Comment by mouse07410** [comment]
> Note that you can read the draft already here as CI builds it for us.

Excellent, thanks!

I assume you tried to reproduce the error **not** from behind a firewall?

If you're new to this tooling - you probably got it from somewhere? Would it be possible to report this problem there?

**Comment by bwesterb** [comment]
> I assume you tried to reproduce the error **not** from behind a firewall?

Exactly.

> If you're new to this tooling - you probably got it from somewhere? Would it be possible to report this problem there?

It’s [Martin’s template](https://github.com/martinthomson/internet-draft-template).
